display_information:
  name: chatgpt-slackbot
features:
  bot_user:
    display_name: chatgpt-slackbot
    always_online: false
oauth_config:
  scopes:
    user:
      - search:read
    bot:
      - chat:write
      - files:write
      - files:read
      - channels:history
      - groups:history
      - im:history
      - mpim:history
settings:
  event_subscriptions:
    bot_events:
      - message.channels
      - message.groups
      - message.im
      - message.mpim
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
